<?xml version="1.0" encoding="utf-8"?><Database Name="RSA" Class="DBFileManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=RSA;Integrated Security=True" SettingsObjectName="RSA.Properties.Settings" SettingsPropertyName="RSAConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.myfile" Member="myfiles">
    <Type Name="myfile">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="file_loca" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="create_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>